version: "3.8"

services:
  api:
    build:
      context: .
      target: builder
    image: mohllal/air-quality-service
    env_file: .env.test
    container_name: test_api
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run test
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: mongo:6.0
    environment:
      MONGO_INITDB_DATABASE: airquality
    container_name: test_db
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./docker/test/db/data:/data/db
      - ./docker/test/db/logs:/var/log/mongodb
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 5s