version: "3.8"

services:
 api:
  build:
   context: .
   target: builder
  env_file: .env.dev
  container_name: api
  volumes:
   - ./:/app
   - /app/node_modules
  ports:
   - 3000:3000
  command: npm run dev